
package editor.buildingeditor2;

import editor.handler.MapEditorHandler;
import editor.game.GameFolder;

import javax.swing.*;
import java.io.File;

/**
 * @author Trifindo
 */
public class BuildingEditorChooser {

    public static void loadGame(MapEditorHandler handler) {
        final JFileChooser fc = new JFileChooser();
        if (handler.getLastBuildDirectoryUsed() != null) {
            fc.setCurrentDirectory(new File(handler.getLastBuildDirectoryUsed()));
        }
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fc.setApproveButtonText("Select folder");
        fc.setDialogTitle("Select the game's main folder that was generated with SDSME, DSPRE or similar");
        final int returnVal = fc.showOpenDialog(handler.getMainFrame());
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            String folderPath = fc.getSelectedFile().getPath();
            if (isDPPtFolder(folderPath)) {
                handler.setLastBuildDirectoryUsed(folderPath);
                BuildHandlerDPPt buildHandler = new BuildHandlerDPPt(folderPath);
                final BuildingEditorDialogDPPt dialogDPPt = new BuildingEditorDialogDPPt(handler.getMainFrame());
                dialogDPPt.init(handler, buildHandler);
                dialogDPPt.loadGame(fc.getSelectedFile().getPath());
                dialogDPPt.loadCurrentNsbmd();
                dialogDPPt.updateView();
                dialogDPPt.setLocationRelativeTo(handler.getMainFrame());
                dialogDPPt.setVisible(true);
            } else if (isHGSSFolder(folderPath)) {
                handler.setLastBuildDirectoryUsed(folderPath);
                BuildHandlerHGSS buildHandler = new BuildHandlerHGSS(folderPath);
                final BuildingEditorDialogHGSS dialogHGSS = new BuildingEditorDialogHGSS(handler.getMainFrame());
                dialogHGSS.init(handler, buildHandler);
                dialogHGSS.loadGame(fc.getSelectedFile().getPath());
                dialogHGSS.loadCurrentNsbmd();
                dialogHGSS.updateView();
                dialogHGSS.setLocationRelativeTo(handler.getMainFrame());
                dialogHGSS.setVisible(true);
            } else if (isBWFolder(folderPath)) {
                handler.setLastBuildDirectoryUsed(folderPath);
                BuildHandlerWB buildHandler = new BuildHandlerWB(folderPath);
                final BuildingEditorDialogWB dialogWB = new BuildingEditorDialogWB(handler.getMainFrame());
                dialogWB.init(handler, buildHandler);
                dialogWB.loadGame(fc.getSelectedFile().getPath());
                dialogWB.setLocationRelativeTo(handler.getMainFrame());
                dialogWB.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(handler.getMainFrame(),
                        "The selected folder is not the game's main folder generated by SDSME, DSPRE or similar",
                        "Error selecting folder", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private static boolean isDPPtFolder(String folderPath) {
        return new GameFolder(folderPath).exists("data" + File.separator + "resource");
    }

    private static boolean isHGSSFolder(String folderPath) {
        return new GameFolder(folderPath).exists("data" + File.separator + "pbr");
    }

    private static boolean isBWFolder(String folderPath) {
        return new GameFolder(folderPath).exists("data" + File.separator + "dl_rom");
    }

}
